language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: 139.59.12.220
after_success:
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_98cd1df60ba8_key -iv $encrypted_98cd1df60ba8_iv
  -in deploy.enc -out deploy -d
