language: node_js
node_js:
  - "6"
addons:
  ssh_known_hosts: 139.59.64.249
after_success:
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh

notifications:
  email:
    - sonisrajan96@gmail.com
    - soni.suryansh11130@gmail.com
